### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by krizzziz** [willemstoker/aps-to-pvoutput#4]
So I am back, sorry for that.

I have 2 pi's over 2 locations. On the first pi the script is working beautifully. On the 2nd Pi, its not.
When adding the script, and changing ECU ID, PVoutput system number and API-key. I tried to run the script. But it gives an error, and I cannot find out why. As mentioned, the exact same script, works on the other system perfect.

`pi@raspberrypi:~/domoticz/scripts/python $ ./apstopvoutput.py
Traceback (most recent call last):
  File "./apstopvoutput.py", line 69, in <module>
    rootdict = getDataFromAPS()
  File "./apstopvoutput.py", line 47, in getDataFromAPS
    response = requests.post(APSYSTEMS_URL, headers=headers, data=data)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.apsystemsema.com', port=8073): Max retries exceeded with url: /apsema/v1/ecu/getPowerInfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x764d8d10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))`

**Comment by obtitus** [comment]
failure is not being able to reach api.apsystemsema.com, so either:

- this pi does not have an internet connection
- something is fishy about the network setup, i.e. firewall, proxy..
- api.apsystemsema.com was down when you tried this
