### ISSUE TITLE
Error between midnight and first unit of power production

### ISSUE THREAD

**Issue by WesselKraaij** [willemstoker/aps-to-pvoutput#6]
The script works fine, however, starting at midnight, the script probably pulls zero entries from EMA until first light and exits with an error. After first light and power production the script runs fine until midnight

Start time: Wed, 17 Mar 2021 06:10:02 GMT Stop time: Wed, 17 Mar 2021 06:10:04 GMT Current status: 1 (Interrupted) Standard output/error:
Traceback (most recent call last):
  File "/-path-/apstopvoutput.py", line 70, in <module>
    timesstring = rootdict.get("data").get("time")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by fdr76** [comment]
Almost 2 years used this script without a problem but on 27 march I get the same errors. It looks that APSystem has changed something. Finally their site is speedy. In the past it was really slow.

Traceback (most recent call last):
 File "/volume1/homes/fdr/scripts/logging-zonnepanelen.py", line 70, in <module>
   timesstring = rootdict.get("data").get("time")
AttributeError: 'NoneType' object has no attribute 'get'

After this error er errors is changed:
Traceback (most recent call last):
 File "/volume1/homes/xxxx/scripts/logging-zonnepanelen.py", line 69, in <module>
   rootdict = getDataFromAPS()
 File "/volume1/homes/xxxx/scripts/logging-zonnepanelen.py", line 48, in getDataFromAPS
   return response.json();
 File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 812, in json
   return complexjson.loads(self.text, **kwargs)
 File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
   return _default_decoder.decode(s)
 File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
   obj, end = self.raw_decode(s)
 File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
   return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


I hope so that AP Systems come with a open documented API.

**Comment by TFHFony** [comment]
Same here. I have been using the script without problems for over a year, but last weekend it has stopped working.

**Comment by WesselKraaij** [comment]
I stumbled upon: 
https://github.com/ksheumaker/homeassistant-apsystems_ecur

Have not tested it yet.

**Comment by TFHFony** [comment]
Hi,

Unfortunately that's for the ECU-R (And I still have the old ECU). And I'm also not using Home Assistent. So for the moment, I've hooked up my APC-EVU2PVO again.

https://sites.google.com/site/ecu2pvo/

**Comment by LauryanFeijen** [comment]
@TFHFony would you care to explain a bit more on how your APC-EVU2PVO works?
From looking at it you are still getting the APS data from the internal network, or are you using the Arduino to listen in on the Zigbee communication?
Would love to see what we can learn from that implementation if that still works and see if and how I could use that same setup on my Raspberry Pi

**Comment by TFHFony** [comment]
As far as I understand, the APC-EVU2PVO uses the APC-ECU's webserver to
read the information from the HTML page and parses this to PVOutput.
