### ISSUE TITLE
No data retrieved

### ISSUE THREAD

**Issue by otello86** [willemstoker/aps-to-pvoutput#7]
Since 26th of march the script retrieve no data from APS API

I have this error when i run the script manually
Traceback (most recent call last):
  File "apstopvoutput.py", line 69, in <module>
    rootdict = getDataFromAPS()
  File "apstopvoutput.py", line 48, in getDataFromAPS
    return response.json();
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Shubhanshu1201** [comment]
I am trying to fetch power data via api `http://api.apsystemsema.com:8073/apsema/v1/ecu/getPowerInfo` but getting error with 404 status code. It seems like for all user this API stops sending the response at same time. Is there any specific reason for this?

**Comment by willemstoker** [comment]
Looks like the EMA app from AP Systems itself is also not working anymore (the app uses the same url, that's how I found this url). I assume they will fix this eventually?

**Comment by TFHFony** [comment]
> Looks like the EMA app from AP Systems itself is also not working anymore (the app uses the same url, that's how I found this url). I assume they will fix this eventually?

It seems a new version of the app has been released today.

**Comment by willemstoker** [comment]
The app is working again!
Is the url working too? Or did they change it?

**Comment by titoj5** [comment]
The previous working URL is still returning a 404 Not Found error.  
http://api.apsystemsema.com:8073/apsema/v1/ecu/getPowerInfo

Do you know if the new app is using a new URL?

**Comment by willemstoker** [comment]
Looks like it's using Amazon cloud now with SSL. It's a bit harder to use that unfortunately.

**Comment by TFHFony** [comment]
Maybe the old server is still up as well and reachable on it's old IP address?

**Comment by otello86** [comment]
The old API continue to response 404 error.
Is it possible to implement the new url in the your script please ?

**Comment by willemstoker** [comment]
Unfortunately I think it's not as simple as changing the URL, because it's now using SSL.
I'm currently busy with other things and I'm not using pvoutput myself anymore.. Maybe some other volunteer can investigate this.

**Comment by otello86** [comment]
Is there another solution to read APS datas and import them into pvoutput or home assistant like Domoticz

**Comment by LauryanFeijen** [comment]
@willemstoker you mention APS is now using AWS and SSL; would you be able to share that URL and what you found out about it? Understand you have other projects, would love to see where others can bring this.
Myself having limited python experience would also like to help, though realistically have to know my limitations.

**Comment by willemstoker** [comment]
> @willemstoker you mention APS is now using AWS and SSL; would you be able to share that URL and what you found out about it? Understand you have other projects, would love to see where others can bring this.
> Myself having limited python experience would also like to help, though realistically have to know my limitations.

You can capute the URL by using an app like this one on your android phone while using the official ECU app:
https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=nl&gl=US

**Comment by otello86** [comment]
Here you will find the new API documentation
I not a developper so if someone would like to investigate on this implementation

[Apsystems EMA API operation manual.pdf](https://github.com/willemstoker/aps-to-pvoutput/files/6287288/Apsystems.EMA.API.operation.manual.pdf)

**Comment by daanvdl** [comment]
When the APS API stopped to work and this script did not work anymore, i wrote my own python script to collect the power-data (incl tempertures and voltages) from the local webpage of my ECU-R and pushes it to pvoutput. 
https://github.com/daanvdl/-ecu2pvoutput
I am not sure it will work on a APS ECU-C.

**Comment by Bandenabos** [comment]
> When the APS API stopped to work and this script did not work anymore, i wrote my own python script to collect the power-data (incl tempertures and voltages) from the local webpage of my ECU-R and pushes it to pvoutput.
> https://github.com/daanvdl/-ecu2pvoutput
> I am not sure it will work on a APS ECU-C.

In your script what do you mean with APIID and SYSTEMID

I got a ECU-R and your script will help me !

**Comment by Shubhanshu1201** [comment]
> Here you will find the new API documentation
> I not a developper so if someone would like to investigate on this implementation
> 
> [Apsystems EMA API operation manual.pdf](https://github.com/willemstoker/aps-to-pvoutput/files/6287288/Apsystems.EMA.API.operation.manual.pdf)

I am able to use  http://installerapi.apsystemsema.com:8074/apsema/v1/apiecu/getEcuPowerDetail api from the documentation which return data for all previous days except current days and is returning data. 
But when i try to use  http://installerapi.apsystemsema.com:8074/apsema/v1/apiecu/getCurrentInfoByEcuList API for current day it is returning 204 status with No content. 
Is there any way to fetch data for current date?

**Comment by Bandenabos** [comment]
I try to use the api but an "apiuserid" is needed. The support can only give userid to professionnal (installer) and I'm just au poor end user !
Have you got a user id ?

**Comment by Shubhanshu1201** [comment]
> I try to use the api but an "apiuserid" is needed. The support can only give userid to professionnal (installer) and I'm just au poor end user !
> Have you got a user id ?

yes, i do have userId and using it to fetch access token

**Comment by Shubhanshu1201** [comment]
Any update on this, how we can retrive power data for current day for any systemId?
